
[light_sources]
	entities = true
	self = true
	block_entities = true
	water_sensitive_check = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				player = true
				villager = true
				armor_stand = true
				skeleton = true
				spider = true
				enderman = true
				zombie = true
				pig = true
				glow_squid = true
				cod = true
				drowned = true
				painting = true
				creeper = true
				squid = true
				bat = true
				chicken = true
				sheep = true
				horse = true
				item = true
				arrow = true
				cow = true
				vindicator = true
				pillager = true
				evoker = true
				illusioner = true
				chest_minecart = true
				item_frame = true
				cave_spider = true
				fox = true
				witch = true
				salmon = true
				wolf = true
				slime = true

			[light_sources.settings.entities.alexsmobs]
				flying_fish = true
				lobster = true
				bison = true
				cockroach = true
				fly = true
				raccoon = true
				komodo_dragon = true
				terrapin = true
				blue_jay = true
				grizzly_bear = true
				centipede_head = true
				centipede_body = true
				centipede_tail = true

			[light_sources.settings.entities.enemyexpansion]
				crawler = true
				slugger = true
				direwolf = true
				intruder = true
				troll = true
				faller = true
				sprinter = true
				huntsman = true
				vampire = true
				botfly = true
				silverqueen = true
				vampflyer = true
				vampbiter = true

			[light_sources.settings.entities.create]
				stationary_contraption = true
				super_glue = true

			[light_sources.settings.entities.quark]
				glass_frame = true
				forgotten = true

			[light_sources.settings.entities.friendsandfoes]
				rascal = true

			[light_sources.settings.entities.steam_powered]
				giant_crab = true
				tri_wheeler = true

			[light_sources.settings.entities.cardiac]
				life_orb = true

